dist: xenial
language: python
python: 3.7
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$TRAVIS_BUILD_DIR/.tox"
before_install:
- mkdir -p $HOME/opt/local/bin
- export PATH=$HOME/opt/local/bin:$PATH
- pushd /tmp/ && git clone https://github.com/rofl0r/proxychains-ng.git && cd proxychains-ng
  && ./configure --prefix=$HOME/opt/local && make -j2 && make install && popd
- pip install shadowsocks
- cp scripts/slackbot-test-ctl $HOME/opt/local/bin
- slackbot-test-ctl init
- slackbot-test-ctl startproxy
install: pip install tox
script:
  - |
    if [[ $TRAVIS_TAG == "" ]]; then
      tox
    fi
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bluesliverx
  password:
    secure: "CNV7kcCVHRZLhnwEDkUGRI8u5hC2K9cSZJCskQidabXtIKoG1IiaTfGFO6dKhaJKqO3NLGmm/xVtGXjqS6oNGbzHR+8ka5TiwH8u8B4oNFP277G5iSiujQjluJFCoN2YWTNcf1iVo2oy3ofinR41YWcPygw1snjOzK+nzfIbVLgpm4i1XrR5Ruyy/XAOWt7treVfj73DlW5795zACSXIDvs5OyT8M0fZP2syHIKKdxDekZSF82cOHtjYCNzu25zdi2esoIAz1FJGtLs1YI/Ed7wQp4vDxghyxHdYaMTFsJhwPxvQR7kQqtc4+RS5HrBQIiY0tgbOHIIdvB3AnWsW9KmPAAsFSk3wlxQ6YVPh3EclVTjfqFA+AooAgwaRnjgVADMHTRtO8Gkcc9TWoDLuWmKPf2H20e0U8nkK8FghXzoKza28LBPfewTeW/lWVTGKHYypm5txZ1lcUxvnhPPi7Na4T3pUVRq2W+X3uZ7Qevf4ggkbDafvW4wveOzdYRqtbBOEW/BDsbhdUJ1OkjFBNnleHWClPSdughGfmt+wRCcbWiQKtMrbpLj/I//C8XNLSTMJk9Xz7f3/Sjj3iNbPrbB7yN7qRzxlVAvVgYJlp4foxaBX2LWjuFQtpRcsi+YYdB1dl/qJz9m6NCBwiokilvqdox5TbHXa0Cd5CK+Gq6c="
  on:
    tags: true
    repo: bluesliverx/oncall-slackbot
