#!/bin/bash
# This is meant to be used from travis only
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
echo "Building base docker image..."
docker build -t $BASE_IMAGE_NAME-base:latest .
echo "Building bot image..."
docker build -t $BASE_IMAGE_NAME:latest --build-arg FROM_IMAGE=$BASE_IMAGE_NAME-base -f Dockerfile-bot .

if [[ $TRAVIS_TAG == "" ]]; then
    echo "Not a tagged build, skipping push"
else
    echo "Pushing images..."
    docker tag $BASE_IMAGE_NAME-base:latest $BASE_IMAGE_NAME-base:$TRAVIS_TAG
    docker tag $BASE_IMAGE_NAME:latest $BASE_IMAGE_NAME:$TRAVIS_TAG
    docker push $BASE_IMAGE_NAME-base:latest
    docker push $BASE_IMAGE_NAME:latest
    docker push $BASE_IMAGE_NAME-base:$TRAVIS_TAG
    docker push $BASE_IMAGE_NAME:$TRAVIS_TAG
fi
